<a href="https://colab.research.google.com/github/navneetk2001/Machine-Learning/blob/master/Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from sklearn import preprocessing

In [4]:
x= np.array([[1., -1., 2.],
             [2., 0., 0.],
             [0., 1., -1.]])

In [10]:
x_scaled = preprocessing.scale(x) # scale makes values centres around mean, basically makes mean to be 0 and variance(standard deviation) to be 1
x_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
x_scaled.mean(axis = 0)   # mean will be 0

array([0., 0., 0.])

In [8]:
x_scaled.std(axis = 0)    # Standard deviation will be 1

array([1., 1., 1.])

In [9]:
scaler = preprocessing.StandardScaler()
scaler.fit(x)

scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [11]:
x_test = [[1, 1, 0]]        # transform testing data using same parameter that you use for training data
scaler.transform(x_test)

array([[ 0.        ,  1.22474487, -0.26726124]])