<a href="https://colab.research.google.com/github/navneetk2001/Machine-Learning/blob/master/Linear%20Regression_ML_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name :- Navneet Kumar
# Roll No :- 102083053
# Group :- 3COE-24

# **Machine Learning :- Assignment 5**

**Question** **1 (Simple Linear Regression) :-**

Q1) Implement the Simple Linear Regression for the data given below and predict the house price for a house with plot size 3000, 2000 and 1500 feet:-

In [1]:
import pandas as pd
import numpy as np

In [15]:
# mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [52]:
#importing dataset
df = pd.read_csv("drive/MyDrive/Colab Notebooks/CSV/Assignment_5 Part_1_Data.csv")
print(df)

   House Price in $1000s (X)  Square feet (Y)
0                        245             1400
1                        312             1600
2                        279             1700
3                        308             1875
4                        199             1100
5                        219             1550
6                        405             2350
7                        324             2450
8                        319             1425
9                        255             1700


In [54]:
#splitting dataset in x and y and converting 1 d array to 2d array using reshape function
x = np.array(df['Square feet (Y)']).reshape((-1, 1)) 
print(x)
y = np.array(df['House Price in $1000s (X)'])
print(y)

[[1400]
 [1600]
 [1700]
 [1875]
 [1100]
 [1550]
 [2350]
 [2450]
 [1425]
 [1700]]
[245 312 279 308 199 219 405 324 319 255]


In [55]:
#importing Linear Regression module for analysis
from sklearn.linear_model import LinearRegression
algo = LinearRegression()
algo.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [56]:
# Calculating coefficient of determination for training data x and y
COD = algo.score(x, y)
print('Coefficient of Determination:', COD) 

Coefficient of Determination: 0.5808173118722721


In [57]:
print('Intercept:', algo.intercept_)              # It will give value of intercept (c) in y = m*x + c
print('Slope:', algo.coef_)                       # It will give value of slope (m) in y = m*x + c

Intercept: 98.24832962138078
Slope: [0.10976774]


In [58]:
# predicted result of above given training data
y_predicted = algo.predict(x)
print('predicted result:', y_predicted, sep='\n')

predicted result:
[251.92316258 273.87671015 284.85348393 304.06283805 218.99284123
 268.38832326 356.20251352 367.17928731 254.66735603 284.85348393]


In [59]:
# New testing Data to predict the house price for a house with given plot size
x_test = np.array([3000,2000,1500]).reshape((-1, 1))
print(x_test)

[[3000]
 [2000]
 [1500]]


In [60]:
# predicted result of above given testing data  
y_test = algo.predict(x_test)
print(y_test)

[427.55154311 317.78380528 262.89993637]


In [61]:
#performing the performance evaluation of the trained algorithm
from sklearn import metrics
print(metrics.mean_squared_error(y_predicted,y))
print(metrics.mean_absolute_error(y_predicted,y))
print(np.sqrt(metrics.mean_squared_error(y_predicted,y)))
print(metrics.r2_score(y_predicted, y))

1366.5565224307989
31.03811644925231
36.96696528565469
0.2782882335643776


**Question 2 (Multiple Linear Regression) :-**

Q2) Implement the Multiple Linear Regression for the data given below and predict the stock index
price if interest rate is 1.5 and unemployment rate is 5.8.

In [66]:
#importing dataset
df1 = pd.read_csv("drive/MyDrive/Colab Notebooks/CSV/Assignment_5 Part_2_Data.csv")
print(df1)

    Year  Month  Interest_Rate  Unemployment_Rate  Stock_Index_Price
0   2017     12           2.75                5.3               1464
1   2017     11           2.50                5.3               1394
2   2017     10           2.50                5.3               1357
3   2017      9           2.50                5.3               1293
4   2017      8           2.50                5.4               1256
5   2017      7           2.50                5.6               1254
6   2017      6           2.50                5.5               1234
7   2017      5           2.25                5.5               1195
8   2017      4           2.25                5.5               1159
9   2017      3           2.25                5.6               1167
10  2017      2           2.00                5.7               1130
11  2017      1           2.00                5.9               1075
12  2016     12           2.00                6.0               1047
13  2016     11           1.75    

In [69]:
#splitting dataset in x by taking features required to predict stock price
x=df1.iloc[:,2:4]
x

Interest_Rate  Unemployment_Rate
0            2.75                5.3
1            2.50                5.3
2            2.50                5.3
3            2.50                5.3
4            2.50                5.4
5            2.50                5.6
6            2.50                5.5
7            2.25                5.5
8            2.25                5.5
9            2.25                5.6
10           2.00                5.7
11           2.00                5.9
12           2.00                6.0
13           1.75                5.9
14           1.75                5.8
15           1.75                6.1
16           1.75                6.2
17           1.75                6.1
18           1.75                6.1
19           1.75                6.1
20           1.75                5.9
21           1.75                6.2
22           1.75                6.2
23           1.75                6.1

In [71]:
#splitting dataset in y
y=pd.DataFrame(df1.iloc[:,4])
y

Stock_Index_Price
0                1464
1                1394
2                1357
3                1293
4                1256
5                1254
6                1234
7                1195
8                1159
9                1167
10               1130
11               1075
12               1047
13                965
14                943
15                958
16                971
17                949
18                884
19                866
20                876
21                822
22                704
23                719

In [72]:
#Loading Linear Regression model for analysis of data
algo1 = LinearRegression()
algo1.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [73]:
COD = algo1.score(x, y)
print('Coefficient of Determination:', COD)              # Calculating coefficient of determination for training data x and y
print('Intercept:', algo1.intercept_)                    # Value of Intercept (c) in y = m1*x1 + m2*x2 + c
print('Slope:', algo1.coef_)                             # Slope (Coefficient) of both the features i.e. m1 of x1 and m2 of x2 in y = m1*x1 + m2*x2 + c

Coefficient of Determination: 0.8976335894170216
Intercept: [1798.40397763]
Slope: [[ 345.54008701 -250.14657137]]


In [74]:
# predicted result (stock price) of above given training data
y_predicted = algo1.predict(x)
print('predicted result:', y_predicted, sep='\n')

predicted result:
[[1422.86238865]
 [1336.47736689]
 [1336.47736689]
 [1336.47736689]
 [1311.46270976]
 [1261.43339548]
 [1286.44805262]
 [1200.06303087]
 [1200.06303087]
 [1175.04837373]
 [1063.64869484]
 [1013.61938057]
 [ 988.60472343]
 [ 927.23435881]
 [ 952.24901595]
 [ 877.20504454]
 [ 852.1903874 ]
 [ 877.20504454]
 [ 877.20504454]
 [ 877.20504454]
 [ 927.23435881]
 [ 852.1903874 ]
 [ 852.1903874 ]
 [ 877.20504454]]


In [76]:
# New testing Data to predict the stock price for given data
x_test=pd.DataFrame(np.array([1.5,5.8]).reshape(1,2),columns=["Interest_Rate","Unemployment_Rate"])
x_test

Interest_Rate  Unemployment_Rate
0            1.5                5.8

In [79]:
# predicted result of above given testing data
y_test=algo1.predict(x_test)
result=pd.DataFrame(y_test,columns=['Stock_Index_Price'])
result

Stock_Index_Price
0         865.863994

In [80]:
#final result
pd.concat([x_test,result],axis="columns")

Interest_Rate  Unemployment_Rate  Stock_Index_Price
0            1.5                5.8         865.863994

In [81]:
#performing the performance evaluation of the trained algorithm
from sklearn import metrics
print(metrics.mean_squared_error(y_predicted,y))
print(metrics.mean_absolute_error(y_predicted,y))
print(np.sqrt(metrics.mean_squared_error(y_predicted,y)))
print(metrics.r2_score(y_predicted, y))

4356.611357123124
51.77251657344109
66.00463133086286
0.885959692473784
